[package]
name = "exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rand = "0.8"
thiserror = "1.0"
log = "0.4"
serde = { workspace = true }
serde_json = "1.0.116"
serde_yaml = { workspace = true }
